### ISSUE TITLE
getPhotos return an error http 500 on a RETS 1.8 server

### ISSUE THREAD

**Issue by joseflexa** [sbruno81/rets-client#15]
Hi.

First of all thanks for rets-client. It is a very nice software ;-)
I have the following test code to get images associated with a ListingID:
```javascript
var rets = require('rets-client');
var util = require('util');
var clientSettings = {
    loginUrl: 'http://sef.rets.interealty.com/Login.asmx/Login',
    username: 'xxxx',
    password: 'yyyy',
    version: 'RETS/1.8',
    userAgent: 'PHRETS/1.0',
    userAgentPassword: 'zzzz'
};
rets.getAutoLogoutClient(clientSettings, function(client) {
  return client.objects.getPhotos("Property", "Photo", process.argv[2]);
}).then(function(result) {
  console.log(util.inspect(result));
  console.log("Done");
});
```

By running this code against a 1.8 RETS server I get the following:
```
$ node test.js A2198880
debug: RETS login
debug: RETS getObject stream Type=Photo, Id=A2198880:*, Resource=Property
debug: RETS getObject error:
Error while attempting search - HTTP Status 500 returned (Internal Server Error)
debug: RETS logout
debug: Logout success
Unhandled rejection RetsServerError: Error while attempting search - HTTP Status 500 returned (Internal Server Error)
  at Request.responseHandler (/Users/flexa/rets-client/node_modules/rets-client/lib/utils/retsHttp.coffee:43:19)
  at emitOne (events.js:82:20)
  at Request.emit (events.js:169:7)
  at Request.onRequestResponse (/Users/flexa/rets-client/node_modules/rets-client/node_modules/request/request.js:951:10)
  at emitOne (events.js:77:13)
  at ClientRequest.emit (events.js:169:7)
  at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
  at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
  at Socket.socketOnData (_http_client.js:305:20)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at TCP.onread (net.js:523:20)
```

I know there were recent changes on the getPhotos call. Do you have a clue on how to debug this?

Thanks in advance

**Comment by zacronos** [comment]
Hi @joseflexa,

From that debug output, it looks like the RETS server is returning an HTTP 500 error.  So there are only 2 possibilities:
* there is something wrong with the way `rets-client` is crafting the query for the photo
* the problem is on the RETS server side

Off the top of my head, I wouldn't expect to get an HTTP error from an improper query.  There are lots of RETS error codes, and most malformed queries should cause one of them.  But this is an HTTP error instead.

So as a first step, I would suggest you contact tech support for your RETS access.  If the problem is on their side, that will be the best way to get it resolved.  Even if the problem is actually something in how the query is formed by `rets-client`, tech support might be able to tell you what is incorrect.  Any information they can provide in that case would help us dig in and fix it.

**Comment by joseflexa** [comment]
Hi @zacronos,

Thank you for the quick answer.

For the sake of comparison I've implemented the same photo retrieval routine using PHRETS pointing to the same server and got it working. Also I tcpdumped both the PHRETS and the rets-client photo retrieval calls so I can compare and see what I am missing.

**Comment by zacronos** [comment]
Great idea!  If you have time, please share the differences you find between the PHRETS calls and the rets-client calls.  I intend to rework the `getObject`/`getPhotos` code at some point (probably in the next few months), as I'm aware of some limitations in the current code -- I'd love to fix the bug you've found while I'm at it.

**Comment by zacronos** [comment]
Ok, I've rearranged some things in my work queue, and I'm going to start trying to refactor the `getObject`/`getPhotos` code tomorrow rather than a couple months from now.  @joseflexa, if you have anything you've discovered from the tcpdump that might be useful, please send it my way.

Feel free to email me directly if you just want to send me the dump files and let me dig through them.

**Comment by joseflexa** [comment]
Joe,

Thanks for the rearrangement.

Here is sample dump of call which if failing on the rets-client (it
produces a http 500) and is not failing on PHRETS.

I changed the parameters to anonymize the call:

        GET
/GetObject.asmx/GetObject?Resource=Property&Type=Photo&ID=9999999%3A%2A&Location=0
HTTP/1.1

        Host: def.zzz.com

        Authorization: Digest username="xxxx", realm="rets@def.zzz.com",
nonce="77ddc88070075c2bb2e200586f832370c",
uri="/GetObject.asmx/GetObject?Resource=Property&Type=Photo&ID=9999999%3A

%2A&Location=0", cnonce="N2QwMDllMzA4MjBkZDQ2MzRiMTVmMDg0NDUWOWUxYWM=",
nc=0009909, qop=auth, response="23eb99bb1098721f6340b09e527f0e61",
opaque="cb6870d0-b391-4c92-a7f7-3b67f906b1f8"

        User-Agent: PHRETS/1.0

        RETS-Version: RETS/1.8

        Accept-Encoding: gzip

        Accept: */*

        RETS-UA-Authorization: Digest z4f45121a301ae94571d5b9be7e63aa3

        Cookie: ASP.NET_SessionId=v3orqdtxkfcqsoffred3po2r;
RETS-Session-ID=v2orqdtxkfcqsoffred3po1z

**Comment by joseflexa** [comment]
Joe,

**Comment by zacronos** [comment]
@joseflexa, thanks.  Is that the rets-client call, or the PHRETS call?  Can you provide a tcpdump of the other one for comparison?

**Comment by zacronos** [comment]
@joseflexa, ok I may have found the problem.  I've cut a v3.2.4 release with the fix, please give it a try and let me know if it works for you now.

**Comment by joseflexa** [comment]
Joe,

I updated but it seems the fix did not worked. I will produce more dump to
send you later.

Regards,
José

**Comment by zacronos** [comment]
Ok, thanks.  Meanwhile I'll work on making deeper changes to the `getObject()` code -- with luck, I'll wind up fixing the problem you're hitting through my changes.

FYI, I don't see this problem on the RETS server I'm using, though it is a 1.7.2 server instead of 1.8, so maybe that is the difference.

**Comment by zacronos** [comment]
Hi @joseflexa -- we've released v4.0 of rets-client, with reworked object/photo handling.  Please give it a try and see if it solves this issue (though you'll have to make some changes to use 4.0).

If it doesn't work, I've also added some debugging features that should make it much easier to capture the request and response headers.  Details are in the [debugging](https://github.com/sbruno81/rets-client#debugging) section of the README.

**Comment by joseflexa** [comment]
Hi Joe,

Happy New Year!

Thanks for the release.

I am adapting my test to the new code. As soon as I have an output I will
return to you.

Regards
José

**Comment by joseflexa** [comment]
Joe,

Hi.
The issue remains with version 4.0. I will dig for more information and
post it to you.

Thanks
José

**Comment by zacronos** [comment]
Ok, thanks.  If you would follow the steps to turn on HTTP request and response header logging as described [here](https://github.com/sbruno81/rets-client#debugging) and then send me the console output, I expect it will have something useful.
